name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # TODO: enable for all supported versions
        python-version: [ "3.8" ] # [ "3.8", "3.9", "3.10" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.11
      - name: Build & Publish Project
        run: |
          poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
