name: Test Python Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # TODO: enable for all supported versions
        python-version: [ "3.8" ] # [ "3.8", "3.9", "3.10" ]
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.11
      - name: Install dependencies
        run: |
          poetry install --no-root
      - name: Perform typing check
        run: |
          poetry run mypy
      - name: Perform tests
        run: |
          poetry run pytest
